version: '3'
services:
  database:
    image: postgres:14-alpine
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres:/var/lib/postgresql/data
    expose:
      - 5432

  app:
    image: node:lts-alpine
    working_dir: /app
    container_name: app_v1
    volumes:
      - .:/app
    ports:
      - 3000:35000
    command: ["yarn", "docker:prod"]

volumes:
  postgres:
